schunkdiscover_amd64:

  only:
    - master
    - tags
    - triggers # for manual triggers

  variables: 
    IMAGE_NAME: "schunkdiscover"
    ARCH: "amd64"
    BASE_IMAGE_NAME: "python:3.10.7-slim"

  stage: build

  services:
    - docker:dind

  script:
    - echo $DEPLOY_PW | docker login -u $DEPLOY_USER --password-stdin $REGISTRY
    - PACKAGE_VERSION=$(eval $VERSION_LOGIC)
    - echo "Building amd64 image"
    - echo $DEPLOY_PW | docker login -u $DEPLOY_USER --password-stdin $REGISTRY
    - IMAGE_TAG=$(eval $VERSION_LOGIC)
    - docker pull $BASE_IMAGE_NAME || true
    - >
      docker build 
      -f Dockerfile.buildDEB
      --tag ${REGISTRY}/${IMAGE_PREFIX}-${IMAGE_NAME}-${ARCH}:${IMAGE_TAG}
      --no-cache
      --build-arg BASE_REGISTRY=${REGISTRY}
      --build-arg BASE_IMAGE_NAME=${BASE_IMAGE_NAME}
      --build-arg BASE_ARCH=${ARCH}
      --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
      --build-arg USER=${DEPLOY_USER}
      --build-arg PW=${DEPLOY_PW}
      .
