variables:
  DEPLOY_USER: ${NEXUSUSER}
  DEPLOY_PW: ${NEXUSPW}
  VERSION_LOGIC: '(if [ "$${CI_COMMIT_TAG}" == ""  ] || [ ${CI_PIPELINE_TRIGGERED} ] ; then echo "latest"; else echo "$${CI_COMMIT_TAG}"; fi);'
  BASE_IMAGE_NAME: "python:3.10.7-slim"
  BASE_IMAGE_TAG: latest
  IMAGE_PREFIX: "tf-grasp-sensor"
  IMAGE_NAME: "rcdiscover"
  
stages:
  - build

include:
  - local: ".gitlab-ci-amd64.yml"
